saitokazumasa/tabisketch

.gitignore
package-lock.json
package.json
src/main/resources/static/css/input.css
src/main/resources/static/css/tailwind.css
tailwind.config.js

close https://github.com/saitokazumasa/tabisketch/issues/6
- tailwind css を導入
`npx tailwindcss -i .\src\main\resources\static\css\input.css -o .\src\main\resources\static\css\tailwind.css --watch`

tailwind css を導入

---

README.md

README に Tailwind CSS について記載

---

.github/ISSUE_TEMPLATE/feature_request_temp.md

issue template を追加

---

src/main/resources/static/css/input.css
src/main/resources/static/css/tailwind.css
tailwind.config.js

close #4 
- colors の設定
- fontFamily の設定

tailwind.config の設定

---

src/main/resources/static/css/input.css
src/main/resources/static/css/tailwind.css
tailwind.config.js

close #14 
- font を body に設定
- w-32 に設定
- font-size 指定なし

tailwind button components の作成

---

src/main/resources/static/css/input.css
src/main/resources/static/css/tailwind.css
tailwind.config.js

close #16 
- border padding の設定
- font-size、width 設定なし
image

tailwind input components の作成

---

src/main/resources/templates/fragment/head.html

- タイトルの設定
- tailwind.cssの読み込み
- faviconの設定
- フォントの設定
#21
- thymeleafの適用

headをlayout化させた

---

pom.xml

close　#24 
- pom.xmlにSpringSecurityとlombokの依存関係を追加
- 自身でWebSecurityConfigとControllerを準備し、動作するか確認してほしい。
- lombokも追加しているので正しく動作しているか確認してほしい(例:@Getter,@Setterを付与したクラスを作成しGetterとSetterが自動的に定義されているか確認する)
画面あるわけではないので割愛します

SpringSecurityとlombokの追加

---

tailwind.config.js

close　None
ローカルのクラス定義の整備が整っていなかったため標準設定のためのプルリク
- フォントカラーの追加
- ページ標準の文字色:default
- リンクがホバーされた時の色:link-hover
- レスポンシブデザインのためのスマホサイズの追加
- スマホサイズとの境界390px:sp
(コミットメッセージに書き忘れ)
- sp用デフォルトフォントサイズの適用:sp-default
None

フォントカラーやフォントサイズの追加

---

.gitignore
README.md
pom.xml
src/main/java/com/tabisketch/bean/User.java
src/main/java/com/tabisketch/mapper/IUsersMapper.java
src/main/java/com/tabisketch/security/LoginUserDetails.java
src/main/java/com/tabisketch/security/LoginUserDetailsService.java
src/main/java/com/tabisketch/security/WebSecurityConfiguration.java
src/main/resources/application.properties
src/test/java/com/tabisketch/security/LoginUserDetailsServiceTest.java

close https://github.com/saitokazumasa/tabisketch/issues/37
- WebSecurityConfig を実装
- LoginUserDetails を実装
- LoginUserDetailsService を実装
- MyBatis / PostgreSQL の依存関係を追加
- ~~application.properties を ignore~~
- IUsersMapper を簡易的に実装
- https://github.com/saitokazumasa/tabisketch/issues/2 を参考に DATABASE "tabisketch" と Users テーブルを作成すること
- README.md を参考に ~~application.properties~~ 環境変数 を設定すること
特になし

セキュリティ設定を実装

---

src/main/java/com/tabisketch/controller/IndexController.java

close #43
- IndexControllerを作成しました
画面はないので割愛

IndexControllerの作成

---

src/main/java/com/tabisketch/controller/LoginController.java

close　#44 
- Loginページのコントローラーです
- 動作確認してほしいです
画面があるわけではないので割愛

logincontrollerの作成

---

tailwind.config.js

close　#55 
- screens（sm）の指定をextendの直下に移動
None

Tailwind config の修正

---

src/main/resources/templates/fragment/footer.html

close #20 
- footerのレイアウトを作成
- レスポンシブデザイン

footerのレイアウトを作成

---

src/main/resources/static/css/common.css
src/main/resources/templates/User/create.html
src/main/resources/templates/fragment/head.html
src/main/resources/templates/login.html
tailwind.config.js

close #60 
- headに1E1E1Eを設定し、デフォルトのフォントカラーを適用
- tailwind.configのdefaultは使用しなくなったため削除
- 既存のtext-defaultを使用していた箇所を削除
None

headにデフォルトのフォントカラーを適用

---

src/main/resources/templates/login.html
src/main/resources/templates/user/create.html

close #74 
修正したページ一覧
- create
- login
password-reset-senderについては別でプルリクが出ているのでそちらの方で変更済み
None

最新のレイアウトの呼び出し方に修正

---

src/main/java/com/tabisketch/security/WebSecurityConfiguration.java

- WebSecurityConfig に static コンテンツのパスを追加
なし

WebSecurityConfig に static コンテンツのパスを追加

---

src/main/java/com/tabisketch/bean/entity/Plan.java
src/main/java/com/tabisketch/bean/entity/User.java
src/main/java/com/tabisketch/mapper/IPlansMapper.java
src/main/java/com/tabisketch/mapper/IUsersMapper.java
src/main/java/com/tabisketch/security/LoginUserDetails.java
src/main/java/com/tabisketch/security/LoginUserDetailsService.java
src/test/java/com/tabisketch/mapper/PlansMapperTest.java
src/test/java/com/tabisketch/mapper/UsersMapperTest.java
src/test/java/com/tabisketch/security/LoginUserDetailsServiceTest.java

- Entity Package を作成
- エンティティクラスを Package 下に移動
なし

Entity Package を作成

---

src/main/java/com/tabisketch/security/WebSecurityConfiguration.java

WebSecurityConfigrationの静的ファイル認可の修正

---

src/main/resources/templates/user/edit/password.html

close #88 
- `user/edit/password`にページ作成
- form送信先：`/user/edit/password`
- 現在のパスワード：`currentPassword`
- 新しいパスワード：`password`
- 新しいパスワード（確認）：`rePassword`

パスワード編集画面の作成

---

src/main/resources/templates/user/edit/mail.html

close #88 
- user/edit/mail.htmlを作成
- メールアドレス｛`mail`｝
- 現在のパスワード｛`currentPassword`｝
- form送信先｛`/user/edit/mail-confirm`｝

メールアドレス編集画面の作成

---

.github/SQL.md

close https://github.com/saitokazumasa/tabisketch/issues/2
- SQLコマンドのドキュメントを作成
なし

SQLコマンドのドキュメントを作成

---

README.md
src/main/resources/application.properties

close #113 
- application.popertiesに追加
- readme更新
なし

Google Map API キーの設定

---

src/main/resources/static/js/autocomplete.js
src/main/resources/static/js/modal.js
src/main/resources/templates/fragment/modal.html
src/main/resources/templates/fragment/script.html

close #111 
- modal のinputに場所検索のAPI適用（autocomplete.js）
- modal 閉じたときに inputからfocusを外す

Modal に場所検索の API適用

---

src/main/java/com/tabisketch/controller/CreatePlanController.java
src/main/resources/templates/plan/create.html
src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java

#121 closeしない
- テストデータを作成
- CreatePlanControllerの作成

プラン作成ページのコントローラーを作成

---

src/main/java/com/tabisketch/bean/form/RegisterForm.java
src/main/java/com/tabisketch/bean/valueobject/EncryptedPassword.java
src/main/java/com/tabisketch/controller/RegisterController.java
src/main/java/com/tabisketch/security/WebSecurityConfiguration.java
src/main/java/com/tabisketch/service/IRegisterService.java
src/main/java/com/tabisketch/service/implement/RegisterService.java
src/test/java/com/tabisketch/service/RegisterServiceTest.java

https://github.com/saitokazumasa/tabisketch/issues/49 (まだcloseしない)
- ユーザー新規登録Serviceを作成
- Controller と結合
- 暗号済みパスワードを値オブジェクト化
なし

ユーザー新規登録Serviceを作成

---

README.md
pom.xml
src/main/java/com/tabisketch/bean/valueobject/ServerMailAddress.java
src/main/java/com/tabisketch/configuration/AsyncConfiguration.java
src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
src/main/java/com/tabisketch/controller/RegisterController.java
src/main/java/com/tabisketch/service/ISendRegisterMailService.java
src/main/java/com/tabisketch/service/implement/SendRegisterMailService.java
src/main/resources/application.properties
src/test/java/com/tabisketch/service/SendRegisterMailServiceTest.java

close https://github.com/saitokazumasa/tabisketch/issues/49
- 登録確認メール送信機能を実装

登録確認メール送信機能を実装

---

src/main/java/com/tabisketch/service/IRegisterService.java
src/main/java/com/tabisketch/service/implement/RegisterService.java
src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
src/test/java/com/tabisketch/controller/IndexControllerTest.java
src/test/java/com/tabisketch/controller/ListPlanControllerTest.java
src/test/java/com/tabisketch/controller/RegisterControllerTest.java
src/test/java/com/tabisketch/controller/TopControllerTest.java
src/test/java/com/tabisketch/mapper/PlansMapperTest.java
src/test/java/com/tabisketch/mapper/UsersMapperTest.java
src/test/java/com/tabisketch/service/RegisterServiceTest.java

- エラーハンドリング部分をリファクタ
- テストケースの関数名をリファクタ
- 単体テストに書き換え
なし

エラーハンドリング部分などをリファクタ

---

src/test/java/com/tabisketch/controller/RegisterControllerTest.java
src/test/java/com/tabisketch/mapper/UsersMapperTest.java

close https://github.com/saitokazumasa/tabisketch/issues/129
- テストデータprovide関数をprivateに変更
なし

テストデータprovide関数をprivateに変更

---

src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
src/main/resources/templates/fragment/header.html
src/main/resources/templates/plan/list.html

現段階でできている所まで結合

---

eslint.config.mjs

close #175 
- 別ファイルの関数などを使う際未定義エラーになっていたため、error を warn に
- googleAPIのcallbackで呼び出す関数が未使用エラーになっていたため、error を warn に
なし

ESlintの設定を編集

---

src/main/java/com/tabisketch/controller/ListPlanController.java

close https://github.com/saitokazumasa/tabisketch/issues/180
- controllerでの`@AuthenticationPrincipal`でユーサ名を取得する方法をリファクタ
なし

controllerでの@AuthenticationPrincipalでユーサ名を取得する方法をリファクタ

---

src/main/java/com/tabisketch/bean/entity/Plan.java
src/main/java/com/tabisketch/bean/entity/User.java

close https://github.com/saitokazumasa/tabisketch/issues/169
- Entityクラスの変数をprivateに変更
なし

Entityクラスの変数をprivateに変更

---

src/main/resources/templates/top.html

close #186 
- Thymeleafの呼び出し方を修正
一応スクリーンショット貼っておきます

TopページのThymeleafの呼び出しの修正

---

src/test/java/com/tabisketch/controller/AuthMailAddressControllerTest.java
src/test/java/com/tabisketch/controller/DeletePlanControllerTest.java
src/test/java/com/tabisketch/controller/EditMailAddressControllerTest.java
src/test/java/com/tabisketch/controller/ListPlanControllerTest.java
src/test/java/com/tabisketch/controller/RegisterControllerTest.java
src/test/java/com/tabisketch/service/AuthMailAddressServiceTest.java
src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
src/test/java/com/tabisketch/service/EditMailAddressServiceTest.java
src/test/java/com/tabisketch/service/ListPlanServiceTest.java
src/test/java/com/tabisketch/service/RegisterServiceTest.java
src/test/java/com/tabisketch/service/SendMailServiceTest.java

- @MockBeanが非推奨になったため@MockitoBeanに更新
なし

@MockBeanが非推奨になったため@MockitoBeanに更新

---

src/main/resources/templates/fragment/script.html

close #192 
- callbackが複数あったため、呼び出し時にエラーが出ていたものを修正

googleMapsAPIの呼び出し方修正

---

src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
src/main/java/com/tabisketch/controller/LoginController.java

close https://github.com/saitokazumasa3/tabisketch/issues/235
- ログイン後、エラーページに飛んでしまうバグを修正
なし

ログイン後、エラーページに飛んでしまうバグを修正

---

.run/sql/CreateDaysTable.sql
.run/sql/CreatePlansTable.sql
.run/sql/CreateUsersTable.sql
src/main/java/com/tabisketch/bean/entity/Day.java
src/main/java/com/tabisketch/bean/entity/Plan.java
src/main/java/com/tabisketch/bean/entity/User.java
src/main/java/com/tabisketch/bean/form/RegisterForm.java
src/main/java/com/tabisketch/service/implement/AuthMailAddressService.java
src/main/java/com/tabisketch/service/implement/EditMailAddressService.java
src/main/java/com/tabisketch/util/StringUtils.java

- `@Data` で変数名 `is〇〇` を使うとバグが発生し、getter/setterがうまく生成されないため、`boolean` に `is` を使わないことにした
なし

booleanにisを使わないことにした

---

src/main/java/com/tabisketch/bean/form/CreateDayForm.java
src/main/java/com/tabisketch/bean/response/CreateDayResponse.java
src/main/java/com/tabisketch/bean/response/IResponse.java
src/main/java/com/tabisketch/controller/CreateDayAPIController.java
src/main/java/com/tabisketch/service/ICreateDayService.java
src/main/java/com/tabisketch/service/implement/CreateDayService.java
src/test/java/com/tabisketch/controller/CreateDayAPIControllerTest.java
src/test/java/com/tabisketch/service/CreateDayServiceTest.java

https://github.com/saitokazumasa3/tabisketch/issues/121
- Day作成APIを作成
なし

Day作成APIを作成

---

src/main/java/com/tabisketch/bean/form/CreatePlaceForm.java
src/main/java/com/tabisketch/bean/response/CreatePlaceResponse.java
src/main/java/com/tabisketch/controller/CreatePlaceAPIController.java
src/main/java/com/tabisketch/service/ICreatePlaceService.java
src/main/java/com/tabisketch/service/implement/CreatePlaceService.java
src/test/java/com/tabisketch/controller/CreatePlaceAPIControllerTest.java
src/test/java/com/tabisketch/service/CreatePlaceServiceTest.java

https://github.com/saitokazumasa3/tabisketch/issues/121
- Place作成APIを作成
なし

Place作成APIを作成

---

src/main/resources/static/js/modal.js
src/main/resources/templates/fragment/modal.html

[close #231 
目的地追加modalの処理変更に伴うjs作成 ](https://github.com/saitokazumasa3/tabisketch/issues/242)

ModalのForm部分修正

---

src/main/resources/templates/fragment/popup.html

close #252 
- popup.htmlのformを削除
なし

popup.htmlのformを削除

---

src/main/resources/static/css/input.css
src/main/resources/templates/password-reset/index.html
src/main/resources/templates/register/index.html
src/main/resources/templates/user/edit/mail/index.html
src/main/resources/templates/user/edit/password/index.html

close 
- 突貫ではあるが入力にエラーがあった際のエラー文を表示するようにできている。
- controllerから対応するエラー文を取得して表示することができるようになるのが理想

各エラー文のコメントアウト削除

---

docker/postgresql/sql/02-create-password-reset-tokens-table.sql

close https://github.com/saitokazumasa3/tabisketch/issues/282
https://github.com/saitokazumasa3/tabisketch/pull/281
- password_reset_tokensテーブルのtokenの型をUUIDに変更
なし

password_reset_tokensテーブルのtokenの型をUUIDに変更

---

package-lock.json
package.json

https://github.com/saitokazumasa3/tabisketch/pull/243
- npmライブラリのバージョンを固定
なし

npmライブラリのバージョンを固定

---

.github/CODEOWNERS

codeownersファイルを追加

---

README.md
package.json

dockerの起動・停止をnpmスクリプトに設定

---

src/main/resources/templates/fragment/head.html

close 
- headタグにCSRF対策用にtokenを取得する行追加

CSRF対策の行追加

---

README.md

- README Docker 破棄コマンド部分の説明を変更
なし

README Docker 破棄コマンド部分の説明を変更

---

src/main/java/com/tabisketch/controller/AuthMailAddressController.java
src/main/java/com/tabisketch/mapper/IUsersMapper.java
src/main/java/com/tabisketch/service/IAuthMailAddressService.java
src/main/java/com/tabisketch/service/implement/AuthMailAddressService.java
src/test/java/com/tabisketch/mapper/UsersMapperTest.java
src/test/java/com/tabisketch/service/AuthMailAddressServiceTest.java

- AuthMailAddressServiceの実装し足りない部分を実装
なし

AuthMailAddressServiceの実装し足りない部分を実装

---

cloudbuild.yaml

close #324 
- 環境変数をsecret managerから直接取得するように変更した
特になし

デプロイの際に環境変数が正しく設定されない不具合の修正

---

src/main/java/com/tabisketch/bean/form/EditMailAddressForm.java
src/main/java/com/tabisketch/controller/EditMailAddressController.java
src/main/java/com/tabisketch/service/IEditMailAddressService.java
src/main/java/com/tabisketch/service/implement/EditMailAddressService.java
src/test/java/com/tabisketch/service/EditMailAddressServiceTest.java

- EditMailAddressServiceを見やすいようにリファクタ
なし

EditMailAddressServiceを見やすいようにリファクタ

---

src/main/java/com/tabisketch/controller/EditPasswordController.java
src/main/java/com/tabisketch/service/IEditPasswordService.java
src/main/java/com/tabisketch/service/implement/EditPasswordService.java
src/main/java/com/tabisketch/service/implement/ResetPasswordService.java
src/test/java/com/tabisketch/service/EditPasswordServiceTest.java

- EditPasswordServiceを見やすいようにリファクタ
なし

EditPasswordServiceを見やすいようにリファクタ

---

src/main/java/com/tabisketch/controller/RegisterController.java
src/main/java/com/tabisketch/service/IRegisterService.java
src/main/java/com/tabisketch/service/implement/RegisterService.java
src/test/java/com/tabisketch/service/RegisterServiceTest.java

- RegisterServiceに実装し足りない部分を実装
なし

RegisterServiceに実装し足りない部分を実装

---

src/main/resources/static/js/map.js

close 
- placeIdがあった場合のみmapの描画がonになっていたのでそれを修正して、mapだけを描画をするmodeも作成した
- error表示のコンソールを削除

マップの描画方法を修正

---

README.md
docker/docker-compose.test.yml
docker/docker-compose.yml
docker/test/Dockerfile
package.json

https://github.com/saitokazumasa3/tabisketch/issues/309
- Dockerでjavaのテストを実行するdocker serviceを作成
以下コマンドで、Docker内でjavaのテストを実行する。
```
npm run docker:test
````
なし

Dockerでjavaのテストを実行するdocker serviceを作成

---

src/main/java/com/tabisketch/controller/EditPlanController.java
src/main/resources/templates/plan/edit.html
src/main/resources/templates/plan/present-edit.html

close 
- プラン編集画面の作成（発表用）
- db操作なし・ボタンの機能なし
- マップの経路を確認するよう

プラン編集画面作成（発表用）

---

src/main/resources/templates/plan/create.html
src/main/resources/templates/plan/edit.html

close 
- 終了地点の下に経路情報があったため削除
- おすすめ目的地の東京ディズニーランドのmodal表示修正

プレゼン用の表示修正

---

src/main/java/com/tabisketch/api/DeletePlaceAPIController.java
src/main/java/com/tabisketch/bean/form/DeletePlaceForm.java
src/main/java/com/tabisketch/bean/response/implement/DeletePlaceResponse.java
src/main/java/com/tabisketch/controller/DeletePlanController.java
src/main/java/com/tabisketch/mapper/IPlacesMapper.java
src/main/java/com/tabisketch/service/IDeletePlaceService.java
src/main/java/com/tabisketch/service/implement/DeletePlaceService.java
src/test/java/com/tabisketch/api/DeletePlaceAPIControllerTest.java
src/test/java/com/tabisketch/bean/form/ExampleDeletePlaceForm.java
src/test/java/com/tabisketch/mapper/PlacesMapperTest.java
src/test/java/com/tabisketch/service/DeletePlaceServiceTest.java

close https://github.com/saitokazumasa3/tabisketch/issues/291
- Placeの削除APIを作成
なし

Placeの削除APIを作成

---

src/main/resources/templates/fragment/head.html

close #360 
- headerに使ってるアイコンを使用

faviconの設定

---

src/main/resources/static/js/map.js

[refactor] 公共交通機関のコードを削除

---

src/main/java/com/tabisketch/bean/form/CreatePlaceForm.java
src/main/java/com/tabisketch/bean/form/UpdatePlaceForm.java

close #377 
- DataTimeFormatの追加
なし

LocalTime整形用DateTimeFormatの追加

---

src/main/resources/static/js/modalElement.js

目的地削除のイベント追加

---

docker/bin/docker_compose_build.sh
docker/bin/docker_compose_down.sh
docker/bin/docker_compose_test.sh
docker/bin/docker_compose_up.sh

close https://github.com/saitokazumasa/tabisketch/issues/359
参考: https://github.com/saitokazumasa/tabisketch/pull/364
- docker-composeの読み込み時に明示的にソートするように変更

docker-composeを読み込むbinコマンドを改善

---

.github/workflows/auto_assign.yml

PR自動アサインactionを追加

---

.github/workflows/build_and_run.yml

build_and_run.ymlのenvを更新

---

cloudbuild.yaml

環境変数の変更に伴い、secret managerに保存しているシークレット名を変更した
- close #410

シークレット名を修正

---

src/main/java/com/tabisketch/rest_controller/DeletePlanRestController.java
src/main/java/com/tabisketch/rest_controller/EditPlanRestController.java
src/main/java/com/tabisketch/service/IDeletePlanService.java
src/main/java/com/tabisketch/service/IEditPlanService.java
src/main/java/com/tabisketch/service/implement/DeletePlanService.java
src/main/java/com/tabisketch/service/implement/EditPlanService.java
src/test/java/com/tabisketch/rest_controller/EditPlanRestControllerTest.java
src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
src/test/java/com/tabisketch/service/EditPlanServiceTest.java

プランの所有者以外でも削除・編集できてしまうのを修正

---

src/test/java/com/tabisketch/bean/entity/ExampleEmailVerificationToken.java
src/test/java/com/tabisketch/bean/entity/ExampleNewEmailVerificartionToken.java
src/test/java/com/tabisketch/bean/entity/ExampleResetPasswordToken.java
src/test/java/com/tabisketch/service/CreatePlanServiceTest.java
src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
src/test/java/com/tabisketch/service/EditEmailServiceTest.java
src/test/java/com/tabisketch/service/EditPasswordServiceTest.java
src/test/java/com/tabisketch/service/EditPlanServiceTest.java
src/test/java/com/tabisketch/service/FindOnePlanWithUserServiceTest.java
src/test/java/com/tabisketch/service/ListPlanServiceTest.java
src/test/java/com/tabisketch/service/RegisterServiceTest.java
src/test/java/com/tabisketch/service/ResetPasswordServiceTest.java
src/test/java/com/tabisketch/service/SendEdtiEmailMailServiceTest.java
src/test/java/com/tabisketch/service/SendMailServiceTest.java
src/test/java/com/tabisketch/service/SendResetPasswordMailServiceTest.java
src/test/java/com/tabisketch/service/VerifyEmailServiceTest.java

一部、派生元ブランチの変更が混じっていますが、気にしないでください。
派生元: https://github.com/saitokazumasa/tabisketch/pull/417

サービスのテストの書き方を間違っていたため修正

---

docker/postgresql/sql/11-create-belongings-table.sql
src/main/java/com/tabisketch/bean/entity/Belonging.java

持ち物テーブルをfix

---

docker/postgresql/sql/08-create-departure-points-table.sql
docker/postgresql/sql/09-create-waypoints-table.sql
docker/postgresql/sql/10-create-destination-points-table.sql
src/main/java/com/tabisketch/bean/entity/Belonging.java
src/main/java/com/tabisketch/bean/entity/DeparturePoint.java
src/main/java/com/tabisketch/bean/entity/DestinationPoint.java
src/main/java/com/tabisketch/bean/entity/Waypoint.java

各種テーブルをfix

---

src/main/java/com/tabisketch/bean/form/CreateDeparturePointForm.java
src/main/java/com/tabisketch/bean/form/CreateDestinationPointForm.java
src/main/java/com/tabisketch/bean/form/CreateWaypointForm.java
src/main/java/com/tabisketch/bean/form/CreateWaypointListForm.java
src/main/java/com/tabisketch/bean/form/UpdateDeparturePointForm.java
src/main/java/com/tabisketch/bean/form/UpdateDestinationPointForm.java
src/main/java/com/tabisketch/bean/form/UpdateWaypointForm.java
src/main/java/com/tabisketch/bean/form/UpdateWaypointListForm.java
src/main/java/com/tabisketch/rest_controller/CreateWaypointListRestController.java
src/main/java/com/tabisketch/rest_controller/EditPlanRestController.java
src/main/java/com/tabisketch/rest_controller/EditWaypointListRestController.java
src/main/java/com/tabisketch/service/implement/CreatePlanService.java
src/test/java/com/tabisketch/bean/form/ExampleCreateWaypointListForm.java
src/test/java/com/tabisketch/rest_controller/CreateWaypointListRestControllerTest.java
src/test/java/com/tabisketch/rest_controller/EditPlanRestControllerTest.java
src/test/java/com/tabisketch/rest_controller/EditWaypointListRestControllerTest.java
src/test/java/com/tabisketch/service/CreatePlanServiceTest.java

- https://github.com/saitokazumasa/tabisketch/issues/431
- [不要になりそうなAPIを一旦コメントアウト](https://github.com/saitokazumasa/tabisketch/pull/432/commits/95e421199efbcb4f92bd9e6dd774ffce317d8ed1)
- [Plan作成時に自動でWaypointListも作成されないようにした](https://github.com/saitokazumasa/tabisketch/pull/432/commits/ed4fc2c9d8710be62e1fedcc503c3d0ca202bcd4)

地点周りの各種formを作成
